spring:
  application:
    name: HotelSafe
  datasource:
    url: jdbc:postgresql://localhost/hotelSafe
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    initialize: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: /tmp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/templates/,src/main/resources/static/
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
app:
  upload:
    dir: uploads/hoteis

#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/testdb
#    username: postgres
#    password: root
#    driverClassName: org.postgresql.Driver
#    initialize: true
#
#  sql:
#    init:
#      schema-locations: classpath:/schema-postgresql.sql
#      mode: always
#      platform: postgres
